# Generated by Django 5.0 on 2023-12-15 19:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app_web', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='article',
            name='title',
            field=models.CharField(max_length=10),
        ),
    ]
